# Generated by Django 3.0.6 on 2020-05-28 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100)),
                ('post_introduction', models.CharField(max_length=500)),
                ('post_content', models.TextField()),
                ('post_author', models.CharField(max_length=100)),
                ('post_imagem', models.ImageField(upload_to='post_img/img')),
                ('post_creation', models.DateTimeField(auto_now_add=True)),
                ('post_published', models.BooleanField(default=True)),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posts.Category')),
            ],
            options={
                'ordering': ['-post_name'],
            },
        ),
    ]
